In [133]:
from sklearn.feature_extraction.text import CountVectorizer

In [134]:
from sklearn.feature_extraction.text import TfidfTransformer

In [135]:
from sklearn.naive_bayes import MultinomialNB

In [136]:
import numpy as np

In [137]:
from sklearn.linear_model import SGDClassifier

In [138]:
from sklearn import metrics

In [139]:
categories = [    
    'ensinofundamental', 
    'ensinomedio',    
]

In [140]:
corpus = open("result.txt")
cont_materiais=0
dados_d=[]
target=[]
linha=corpus.readline()
while(linha!=""):

    vetor_saida=[]
    for i in linha.replace("[","").replace("]","").split(","):
        if type(eval(i))==float:
            vetor_saida.append(float(i))
        elif type(i)==str:
            if len(i)==22:
 #               print "fundamental"
                #vetor_saida.append(0)
                target.append(1)
            elif len(i)==16:
#                print "MEDIO"
#                vetor_saida.append(1)
                target.append(2)
    dados_d.append(vetor_saida)
    
    cont_materiais+=1
#    dados.append(linha)
#    dados_d[cont_materiais]=dados
    linha=corpus.readline()
print cont_materiais
    

367


In [141]:
dados_d[0] #64 metricas
len(target)

367

In [142]:
len('ensinomedio') #17enf #11enm

11

In [143]:
X = np.array(dados_d)
y[0]

1

In [108]:
y = np.array(target)

In [109]:
y

array([1, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2,
       1, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2,
       1, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2,
       2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1,
       2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2,
       1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2,
       2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1,
       2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2,
       1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2,
       2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1,
       2, 1,

# Usando  SVM
## 99% precisao

In [144]:
import sys
import os
import time

from sklearn import svm
from sklearn.metrics import classification_report


In [145]:
import numpy as np
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(
    dados_d, target, test_size=0.30, random_state=2018)


In [146]:
#X_train, X_test, y_train, y_test
# Perform classification with SVM, kernel=rbf
classifier_rbf = svm.SVC()
t0 = time.time()
classifier_rbf.fit(X_train, y_train)
t1 = time.time()
prediction_rbf = classifier_rbf.predict(X_test)
t2 = time.time()
time_rbf_train = t1-t0
time_rbf_predict = t2-t1

# Perform classification with SVM, kernel=linear
classifier_linear = svm.SVC(kernel='linear')
t0 = time.time()
classifier_linear.fit(X_train, y_train)
t1 = time.time()
prediction_linear = classifier_linear.predict(X_test)
t2 = time.time()
time_linear_train = t1-t0
time_linear_predict = t2-t1


In [147]:

# Perform classification with SVM, kernel=linear
classifier_liblinear = svm.LinearSVC()
t0 = time.time()
classifier_liblinear.fit(X_train, y_train)
t1 = time.time()
prediction_liblinear = classifier_liblinear.predict(X_test)
t2 = time.time()
time_liblinear_train = t1-t0
time_liblinear_predict = t2-t1

# Print results in a nice table
print("Results for SVC(kernel=rbf)")
print("Training time: %fs; Prediction time: %fs" % (time_rbf_train, time_rbf_predict))
print(classification_report(y_test, prediction_rbf, target_names=categories))
print("Results for SVC(kernel=linear)")
print("Training time: %fs; Prediction time: %fs" % (time_linear_train, time_linear_predict))
print(classification_report(y_test, prediction_linear, target_names=categories))
print("Results for LinearSVC()")
print("Training time: %fs; Prediction time: %fs" % (time_liblinear_train, time_liblinear_predict))
print(classification_report(y_test, prediction_liblinear, target_names=categories))

Results for SVC(kernel=rbf)
Training time: 0.010162s; Prediction time: 0.003316s
                   precision    recall  f1-score   support

ensinofundamental       0.00      0.00      0.00        60
      ensinomedio       0.46      1.00      0.63        51

      avg / total       0.21      0.46      0.29       111

Results for SVC(kernel=linear)
Training time: 18.376302s; Prediction time: 0.001824s
                   precision    recall  f1-score   support

ensinofundamental       0.71      0.33      0.45        60
      ensinomedio       0.52      0.84      0.64        51

      avg / total       0.62      0.57      0.54       111

Results for LinearSVC()
Training time: 0.055468s; Prediction time: 0.000508s
                   precision    recall  f1-score   support

ensinofundamental       0.54      1.00      0.70        60
      ensinomedio       0.00      0.00      0.00        51

      avg / total       0.29      0.54      0.38       111



In [159]:
float(classification_report(y_test, prediction_rbf, target_names=categories).split()[len(classification_report(y_test, prediction_liblinear, target_names=categories).split())-3])

0.46

In [122]:
from sklearn import metrics
print metrics.confusion_matrix(y_test, prediction_linear)

[[27 12]
 [12 23]]


# Predicao
## documentos fora do teste e treino

In [362]:

docs_new = ['@titulo=¿Flota o se hunde?@formatoMat=Experimento prático@componente=Componente curricular nao identificado@etapas=Educação Infantil@descricao=Experimento simples, com a utilização de materiais de baixo custo e de fácil obtenção@autorUpload=Desconhecido@autorMaterial=Antonio Varela@tag=["Volume" "Gravidade" "Densidade" "Educação Infantil" "Natureza e sociedade" "Os fenômenos da natureza"]@formatoComp=application/msword', '@titulo=Heart anatomical structures@formatoMat=Animação/simulação@componente=Componente curricular nao identificado@etapas=Ensino Superior@descricao=Basic anatomy knowledge@autorUpload=Desconhecido@autorMaterial=LearnersTV@tag=["Vein" "Heart" "Ventricle" "Fisiologia" "Educação Superior" "Ciências Biológicas" "Fisiologia Cardiovascular"]@formatoComp=application/vnd.adobe.flash.movie','@titulo=Seven wives and seven prisons; Or<VIRGULA> experiences in the life of a matrimonial monomaniac - Chapter 08@formatoMat=Áudio@componente=Componente curricular nao identificado@etapas=Ensino Médio@descricao=Is a funny story where the author talks about his seven marriages and experiences with their relationships@autorUpload=Desconhecido@autorMaterial=Abbott L.A@tag=["Letras" "English" "Marriage" "Listening" "Relationship" "Ensino Médio" "Produção oral" "Educação Básica" "Compreensão oral" "Língua Estrangeira" "Educação Superior" "Ensino Fundamental Final"]@formatoComp=audio/mpeg', '@titulo=Short poetry collection 003 - Wild nights@formatoMat=Áudio@componente=Componente curricular nao identificado@etapas=Ensino Médio@descricao=Librivox’s Short Poetry Collection 003 is a collection of 20 public-domain poems. Professors or students who want to follow the poetry, by reading, can access the website@autorUpload=Desconhecido@autorMaterial=Emily Dickinson@tag=["Letras" "Poetry" "Literature" "Audiobook" "Séries Finais" "Ensino Médio" "Produção oral" "Educação Básica" "Compreensão oral" "Língua Estrangeira" "Educação Superior" "Ensino Fundamental"]@formatoComp=audio/mpeg','@titulo="Vinte anos da Constituição: inocência perdida [Câmara informa]"@resumo=Apresenta o cenário da reunião da Constituinte passando por sucessos cinematográficos que ainda sofreram censura no Brasil da época. Relata a extinção da censura no paísBrasil após a promulgação da constituinte. Retrata a ascensão de artistas nacionais da televisão, e o sucesso das telenovelas e programas de humor. Trata dos vazamentos e acidentes radioativos de Chernobyl e Goiânia, além dos destaques na música e na publicidade brasileira.@autorUpload=Desconhecido.@autorMaterial=TV Câmara@tags=["Censura" "Política pública" "Ciência Política" "Cultura brasileira" "Políticas Públicas" "Educação Superior" "Ciências Humanas" "Meios de comunicação" "Atitude e Ideologias Políticas"]','@titulo=Sinapse 3D@formatoMat=Animação/simulação@componente=Biologia@etapas=Ensino Médio@descricao=Apresenta, de forma simplificada, o funcionamento de uma sinapse entre um neurônio e uma célula alvo@autorUpload=Desconhecido@autorMaterial=Fundação Centro de Ciências e Educação Superior a Distância do Estado do Rio de Janeiro (CECIERJ)@tag=[\"Biologia\" \"Ensino Médio\" \"Educação Básica\" \"Identidade dos seres vivos\"]@formatoComp=application/zip',"@titulo='[Aulas de Física em Flash] [Aula 1-1] Medições - Introdução'@descricao=='Discute as principais diferenças entre ciência e arte. Mostra que <VIRGULA> enquanto as grandezas físicas podem ser mensuradas <VIRGULA> não podemos quantificar objetivamente e de forma reprodutível as sensações pessoais que surgem da observação de uma obra de arte. Destaca que a medição é parte integrante de nossas vidas <VIRGULA> embora nem sempre percebamos <VIRGULA> e indissociável da atividade científica'"]
#X_new_counts = count_vect.transform(docs_new)
X_new_tfidf = vectorizer.transform(docs_new)
predicted = classifier_liblinear.predict(X_new_tfidf)
for doc, category in zip(docs_new, predicted):
#    print('%r => %s' % (doc, categories[category]))
    for i in doc.split("@"):
        print i
    print category, categories[category-2]
   


titulo=¿Flota o se hunde?
formatoMat=Experimento prático
componente=Componente curricular nao identificado
etapas=Educação Infantil
descricao=Experimento simples, com a utilização de materiais de baixo custo e de fácil obtenção
autorUpload=Desconhecido
autorMaterial=Antonio Varela
tag=["Volume" "Gravidade" "Densidade" "Educação Infantil" "Natureza e sociedade" "Os fenômenos da natureza"]
formatoComp=application/msword
12 Ciencias da Natureza

titulo=Heart anatomical structures
formatoMat=Animação/simulação
componente=Componente curricular nao identificado
etapas=Ensino Superior
descricao=Basic anatomy knowledge
autorUpload=Desconhecido
autorMaterial=LearnersTV
tag=["Vein" "Heart" "Ventricle" "Fisiologia" "Educação Superior" "Ciências Biológicas" "Fisiologia Cardiovascular"]
formatoComp=application/vnd.adobe.flash.movie
5 Biologia

titulo=Seven wives and seven prisons; Or<VIRGULA> experiences in the life of a matrimonial monomaniac - Chapter 08
formatoMat=Áudio
componente=Componente cu

In [ ]:
'@titulo="Vinte anos da Constituição: inocência perdida [Câmara informa]"@resumo=Apresenta o cenário da reunião da Constituinte passando por sucessos cinematográficos que ainda sofreram censura no Brasil da época. Relata a extinção da censura no paísBrasil após a promulgação da constituinte. Retrata a ascensão de artistas nacionais da televisão, e o sucesso das telenovelas e programas de humor. Trata dos vazamentos e acidentes radioativos de Chernobyl e Goiânia, além dos destaques na música e na publicidade brasileira.@autorUpload=Desconhecido.@autorMaterial=TV Câmara@tags=["Censura" "Política pública" "Ciência Política" "Cultura brasileira" "Políticas Públicas" "Educação Superior" "Ciências Humanas" "Meios de comunicação" "Atitude e Ideologias Políticas"]'


# Cross-Validation
## alguns testes e depois o treinamento

In [206]:
from sklearn.model_selection import StratifiedKFold
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

In [218]:
#cvscores = []
#train_data = X_train
#test_data = X_test
#train_labels = y_train
#test_labels = y_test

dados_vec = vectorizer.fit_transform(dados)
#test_vectors = vectorizer.transform(test_data)

#quantidade de K para rodar #Returns the number of splitting iterations in the cross-validator.
#kfold.get_n_splits(dados_vec, rotulo_ind)
for train, test in kfold.split(dados, rotulo_ind):
    print len(train), len(test)

9805 1097
9806 1096
9807 1095
9810 1092
9812 1090
9813 1089
9814 1088
9816 1086
9817 1085
9818 1084


In [219]:
#kfold.get_n_splits(dados_vec, rotulo_ind)
for train, test in kfold.split(dados_vec, rotulo_ind):
    print len(train), len(test)

9805 1097
9806 1096
9807 1095
9810 1092
9812 1090
9813 1089
9814 1088
9816 1086
9817 1085
9818 1084


In [273]:
from sklearn.metrics import accuracy_score


# Read the data
#train_data = dados
#train_labels = rotulo_ind

In [287]:
####teste
dados_np=np.array(dados)
#type(dados_np)
#for train_index, test_index in kfold.split(dados_np, rotulo_ind):
#    print dados_np[train_index]

In [289]:
rotulos_ind_np=np.array(rotulo_ind)

In [ ]:
cvscores = []
# Create feature vectors
vectorizer = TfidfVectorizer(min_df=5,
                             max_df = 0.8,
                             sublinear_tf=True,
                             use_idf=True)


for train_index, test_index in kfold.split(dados_np, rotulo_ind):
    train_vectors = vectorizer.fit_transform(dados_np[train_index])
    test_vectors = vectorizer.transform(dados_np[test_index])

    
    # Perform classification with SVM, kernel=rbf
    classifier_rbf = svm.SVC()
    classifier_rbf.fit(train_vectors, rotulos_ind_np[train_index])
    prediction_rbf = classifier_rbf.predict(test_vectors)
    
    # Perform classification with SVM, kernel=linear
    classifier_linear = svm.SVC(kernel='linear')
    classifier_linear.fit(train_vectors, rotulos_ind_np[train_index])
    prediction_linear = classifier_linear.predict(test_vectors)
    
    # Perform classification with SVM, kernel=linear
    classifier_liblinear = svm.LinearSVC()
    classifier_liblinear.fit(train_vectors, rotulos_ind_np[train_index])
    prediction_liblinear = classifier_liblinear.predict(test_vectors)
    
    # Print results in a nice table
    print("Results for SVC(kernel=rbf)")
    print(classification_report(rotulos_ind_np[test_index], prediction_rbf, target_names=categories))
    print("Results for SVC(kernel=linear)")
    print(classification_report(rotulos_ind_np[test_index], prediction_linear, target_names=categories))
    print("Results for LinearSVC()")
    print(classification_report(rotulos_ind_np[test_index], prediction_liblinear, target_names=categories))
        
    print("%s: %.2f%%" % ("accuracy score", accuracy_score(rotulos_ind_np[test_index], prediction_liblinear)*100))
    cvscores.append(accuracy_score(rotulos_ind_np[test_index], prediction_liblinear)*100) 
    
    
    

In [295]:
print("%.2f%% (+/- %.2f%%)" % (np.mean(cvscores), np.std(cvscores)))

99.22% (+/- 0.15%)


In [220]:
from sklearn.metrics import classification_report
y_true = [0, 1, 2, 2, 2]
y_pred = [0, 0, 2, 2, 1]
target_names = ['class 0', 'class 1', 'class 2']
x=classification_report(y_true, y_pred, target_names=target_names)
print(x)



             precision    recall  f1-score   support

    class 0       0.50      1.00      0.67         1
    class 1       0.00      0.00      0.00         1
    class 2       1.00      0.67      0.80         3

avg / total       0.70      0.60      0.61         5



In [229]:
print classification_report(test_labels, prediction_liblinear, target_names=categories)

                      precision    recall  f1-score   support

          Matematica       0.99      1.00      0.99       640
              Fisica       1.00      1.00      1.00       464
             Quimica       1.00      1.00      1.00       491
            Biologia       1.00      1.00      1.00       479
   Lingua_Portuguesa       0.99      1.00      1.00       444
            Historia       0.97      0.98      0.97       155
              Outros       0.96      0.95      0.96       133
           Geografia       0.99      0.97      0.98        99
      Lingua_Inglesa       1.00      1.00      1.00       105
           Filosofia       1.00      0.98      0.99        62
Ciencias da Natureza       0.98      0.88      0.93        50
          Sociologia       1.00      1.00      1.00        61
     Educacao_Fisica       1.00      0.95      0.97        40
    Lingua_Espanhola       0.97      1.00      0.98        28
                Arte       0.95      0.90      0.92        20

      

In [251]:
from sklearn.metrics import precision_recall_fscore_support
print precision_recall_fscore_support(test_labels, prediction_liblinear,average='weighted')[0]

0.992038058306


In [254]:
from sklearn.metrics import accuracy_score
accuracy_score(test_labels, prediction_liblinear)

0.99205136044023234

In [255]:
print precision_recall_fscore_support(test_labels, prediction_liblinear)[0]

[ 0.98916409  0.99784483  1.          0.99791667  0.99327354  0.96815287
  0.96212121  0.98969072  1.          1.          0.97777778  1.          1.
  0.96551724  0.94736842]


In [257]:
print precision_recall_fscore_support(test_labels, prediction_liblinear,average='micro')[0]

0.99205136044


In [258]:
    print("%s: %.2f%%" % ("accuracy score", accuracy_score(test_labels, prediction_liblinear)*100))

accuracy score: 99.21%


# Criando novo corpus com o classificador
## classificando a categoria que ainda não existe e salvando - são 7927 - apenas para o português

In [355]:
corpus_not_classification = open("13jun_vector_NOT_CLASS.csv")
dados_nao_classificados=[]
linha=corpus_not_classification.readline()
while(linha!=""):
    dados_nao_classificados.append(linha)
    linha=corpus_not_classification.readline()
    
X_new_tfidf = vectorizer.transform(dados_nao_classificados)
predicted = classifier_liblinear.predict(X_new_tfidf)

cont=1
for doc, category in zip(dados_nao_classificados, predicted):
#    print('%r => %s %s' % (doc, category, categories[category-2]))
    print "\n ===> Cont",cont
    for i in doc.split("@"):
        print i
    print category, categories[category-2]
    if cont>40:
        break
    cont+=1



 ===> Cont 1
"
titulo=Bicicletas / Bicycles - Poster 3
formatoMat=Imagem
componente=Componente curricular nao identificado
etapas=Etapas de ensino nao identificado
descricao=Auxiliar no estudo sobre a importância de se reduzir a emissão de gases poluentes na atmosfera substituindo o automóveis por bicicletas
autorUpload=Desconhecido
autorMaterial=Valdinei Calvento
tag=[]
formatoComp=image/jpeg"

4 Quimica

 ===> Cont 2
"
titulo=Buteno
formatoMat=Imagem
componente=Componente curricular nao identificado
etapas=Etapas de ensino nao identificado
descricao=Demontrar a estrutura de uma molécula de Buteno
autorUpload=Desconhecido
autorMaterial=João Paiva
tag=[]
formatoComp=image/jpeg"

5 Biologia

 ===> Cont 3
"
titulo=O futuro é agora - Episódio XIII - Capítulo I - O texto impresso e o virtual
formatoMat=Vídeo
componente=Componente curricular nao identificado
etapas=Etapas de ensino nao identificado
descricao=Este capítulo tem como objetivo específico reconhecer os recursos de escrita e ade

In [328]:
categories[4-2]

'Quimica'

In [338]:
from sklearn import metrics
print metrics.confusion_matrix(test_labels, prediction_liblinear)

[[639   0   0   0   0   0   0   0   0   0   0   0   0   0   1]
 [  0 463   0   0   0   1   0   0   0   0   0   0   0   0   0]
 [  0   0 491   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 479   0   0   0   0   0   0   0   0   0   0   0]
 [  1   0   0   0 443   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   1 152   1   0   0   0   1   0   0   0   0]
 [  2   0   0   0   2   2 127   0   0   0   0   0   0   0   0]
 [  2   0   0   0   0   1   0  96   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0 105   0   0   0   0   0   0]
 [  0   0   0   0   0   1   0   0   0  61   0   0   0   0   0]
 [  1   0   0   1   0   0   3   1   0   0  44   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0  61   0   0   0]
 [  0   1   0   0   0   0   1   0   0   0   0   0  38   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0  28   0]
 [  1   0   0   0   0   0   0   0   0   0   0   0   0   1  18]]


In [347]:
a='"@titulo=Mec\xc3\xa2nica - 2\xc2\xaa Lei de Newton: Aplica\xc3\xa7\xc3\xb5es@formatoMat=Anima\xc3\xa7\xc3\xa3o/simula\xc3\xa7\xc3\xa3o@componente=Componente curricular nao identificado@etapas=Etapas de ensino nao identificado@descricao=Em teoria se fundamentam conceitos, com variados exemplos, contando com acessos a outras fontes selecionadas de informa\xc3\xa7\xc3\xa3o, v\xc3\xaddeos e recursos de imag\xc3\xa9tica, dirigidos para determinados endere\xc3\xa7os na web@autorUpload=Desconhecido@autorMaterial=Cassiano Zeferino de Carvalho Neto <VIRGULA> Instituto Galileo Galilei para a Educa\xc3\xa7\xc3\xa3o (IGGE) <VIRGULA> Jos\xc3\xa9 Maria Filardo Bassalo <VIRGULA> Jos\xc3\xa9 Silv\xc3\xa9rio Edmundo Germano <VIRGULA> Maria Ta\xc3\xads de Melo <VIRGULA> Projeto Condigital MEC \xe2\x80\x93 MCT@tag=[]@formatoComp=application/zip"\n => 3 Fisica'
a[a.index("@titulo=")+len('@titulo='):a.index("@componente")]

'Mec\xc3\xa2nica - 2\xc2\xaa Lei de Newton: Aplica\xc3\xa7\xc3\xb5es@formatoMat=Anima\xc3\xa7\xc3\xa3o/simula\xc3\xa7\xc3\xa3o'

In [344]:
a[a.index("@componente")+len('@componente'):a.index("@componente")]

86

In [348]:
for i in a.split("@"):
    print i

"
titulo=Mecânica - 2ª Lei de Newton: Aplicações
formatoMat=Animação/simulação
componente=Componente curricular nao identificado
etapas=Etapas de ensino nao identificado
descricao=Em teoria se fundamentam conceitos, com variados exemplos, contando com acessos a outras fontes selecionadas de informação, vídeos e recursos de imagética, dirigidos para determinados endereços na web
autorUpload=Desconhecido
autorMaterial=Cassiano Zeferino de Carvalho Neto <VIRGULA> Instituto Galileo Galilei para a Educação (IGGE) <VIRGULA> José Maria Filardo Bassalo <VIRGULA> José Silvério Edmundo Germano <VIRGULA> Maria Taís de Melo <VIRGULA> Projeto Condigital MEC – MCT
tag=[]
formatoComp=application/zip"
 => 3 Fisica
